// <auto-generated />
namespace Bookshelf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class teachersstudents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teachersstudents));
        
        string IMigrationMetadata.Id
        {
            get { return "201708180408270_teachers-students"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
